name: "convert csv to xml"
description: "Convert csv files in data/ to xml and place them into export"

runs:
  using: "composite"
  steps:
    - run: echo "Hello status"
      shell: bash
    - run: python Scripts/convert_all_csv2xml.py -i Spreadsheet/ -o XML/
      shell: bash
