name: "validate csv"
description: "validate csv data"

runs:
  using: "composite"
  steps:
    - run: echo "Validating CSV data"
      shell: bash
    - run: python Scripts/validate_csvs.py Spreadsheet/
      shell: bash --login -eo pipefail {0}
